# Generated by Django 4.2.14 on 2025-06-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
