# Generated by Django 4.2.14 on 2025-06-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_contact',
            field=models.CharField(blank=True, help_text='Provide WhatsApp contact number if you prefer being contacted via WhatsApp.', max_length=15, null=True),
        ),
    ]
